### PR TITLE
Add validation to form email input field

### PR DESCRIPTION
**Pull request by batoolfatima2135**
In this branch, I have implemented a simple validation:
The content of the email field has to be in lowercase.

I also implemented the following interactions:
When the user submits the form, check if the email is in lowercase.

1. If the validation is OK, the form is sent.
2. If the validation is not OK, you show an error message to the user near the submit button informing them of the error and the form is not sent.

### CODE REVIEW

**Review by amejid — COMMENTED** [review]
Hi @batoolfatima2135, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] You have submitted a project, that does not have commits from your coding partner. This activity is supposed to be done collaboratively. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by batoolfatima2135** [comment]
@amejid , This is my solo activity. Microverse has allowed me to do all activities solo this week due to internet connection issues in my country. Attaching an email snapshot also for reference
Screenshot 2023-05-17 064944

**Comment by amejid** [comment]
Hey @batoolfatima2135, I see that you have the green light to work solo. For any activities you are going to submit this week please include this screenshot in the PR description so reviewers can understand the situation. Kindly submit your work for review on the dashboard. Happy coding.

**Review by V-Blaze — APPROVED** [review]
Hi @batoolfatima2135  , 

# Approved 🟢 🟢 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
giphy

## Highlights

- Email validation works💯
-  Pull request summary is descriptive👍
-  Clean organized code🟢 👍

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
